//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/tfc/bbbhop.html
halflife.wad
liquids.wad
xeno.wad
spraypaint.wad
cstrike.wad
cs_dust.wad
cs_assault.wad
cs_havana.wad
timecounter.wad
cs_747.wad
cs_bdog.wad
n0th1ng.wad
cs_cbble.wad
maps/bbbhop.bsp
cs_office.wad
