halflife.wad
gfx/env/clackup.tga
gfx/env/clackdn.tga
gfx/env/clacklf.tga
gfx/env/clackrt.tga
gfx/env/clackft.tga
gfx/env/clackbk.tga
sound/clack/grmusicloop2.wav
sound/clack/grmusicloop1.wav
sprites/clack/{cktree.spr
sprites/laserbeam.spr
sound/clack/grmusicloop3.wav
sound/clack/cicadasloop.wav
sound/clack/treeloop.wav
sprites/clack/{medance.spr
sound/clack/grmusicloop4.wav
models/clack/ckentity1.mdl
sound/clack/grmusicloop7.wav
sound/clack/grmusicloop8.wav
sound/clack/grmusicloop5.wav
sound/clack/grmusicloop6.wav
sound/clack/grmusicloop9.wav
models/player/pike/pike.mdl
models/player/pike/pike.bmp