//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/combat2.html
halflife.wad
liquids.wad
decals.wad
sound/ambience/wind2.wav
sprites/flare1.spr
gfx/env/cliffbk.tga
gfx/env/cliffdn.tga
gfx/env/cliffft.tga
gfx/env/clifflf.tga
gfx/env/cliffrt.tga
gfx/env/cliffup.tga
overviews/combat2.txt
overviews/combat2.bmp
maps/combat2.bsp
