//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/enix.html
halflife.wad
liquids.wad
sprites/glow01.spr
sound/ambience/labdrone1.wav
sound/ambience/wind1.wav
sprites/glow03.spr
sound/ambience/industrial2.wav
sound/ambience/boomer.wav
gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
maps/enix.bsp
