gfx/env/desert01bk.tga
gfx/env/desert01dn.tga
gfx/env/desert01ft.tga
gfx/env/desert01lf.tga
gfx/env/desert01rt.tga
gfx/env/desert01up.tga
models/bigtree.mdl
models/bush16.mdl
sound/cath_birds.wav
sprites/spr1n/digits/kzblt/x0.spr
sprites/spr1n/digits/kzblt/x1.spr
sprites/spr1n/digits/kzblt/x2.spr
sprites/spr1n/digits/kzblt/x3.spr
sprites/spr1n/digits/kzblt/x4.spr
sprites/spr1n/digits/kzblt/x5.spr
sprites/spr1n/digits/kzblt/x6.spr
sprites/spr1n/digits/kzblt/x7.spr
sprites/spr1n/digits/kzblt/x8.spr
sprites/spr1n/digits/kzblt/x9.spr
