//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/gauss_race.html
halflife.wad
sound/ambience/biotone.wav
sound/ambience/warn3.wav
maps/gauss_race.bsp
