//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/justwar2.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
sprites/muzzleflash.spr
maps/justwar2.bsp
