// kz_citadel.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (103):
gfx/env/Bluesky_bk.tga
gfx/env/Bluesky_dn.tga
gfx/env/Bluesky_ft.tga
gfx/env/Bluesky_lf.tga
gfx/env/Bluesky_rt.tga
gfx/env/Bluesky_up.tga
models/start_button.mdl
sound/ambience/8_baller.wav
sound/ambience/abstract_air_loop1.wav
sound/ambience/abstract_air_loop5.wav
sound/ambience/abstract_hit1.wav
sound/ambience/abstract_hit2.wav
sound/ambience/abstract_hit3.wav
sound/ambience/abstract_hit4.wav
sound/ambience/abstract_hit5.wav
sound/ambience/abstract_hit6.wav
sound/ambience/abstract_hit7.wav
sound/ambience/abstract_hit8.wav
sound/ambience/amb_industrial_loop1.wav
sound/ambience/amb_industrial_loop2.wav
sound/ambience/ambience_base.wav
sound/ambience/beer_man_5000.wav
sound/ambience/big_fan1.wav
sound/ambience/citadel_eerie1.wav
sound/ambience/citadel_end_room.wav
sound/ambience/city_tone.wav
sound/ambience/clang_amb1.wav
sound/ambience/clang_amb2.wav
sound/ambience/clang_amb3.wav
sound/ambience/clang_amb4.wav
sound/ambience/clang_amb5.wav
sound/ambience/clang_amb6.wav
sound/ambience/clang_amb7.wav
sound/ambience/clang_amb8.wav
sound/ambience/corridor1.wav
sound/ambience/corridor_loop2.wav
sound/ambience/eerie_wind_loop1.wav
sound/ambience/ez_gme.wav
sound/ambience/fluorescent_hum.wav
sound/ambience/force_field1.wav
sound/ambience/hole_amb3.wav
sound/ambience/hole_hit1.wav
sound/ambience/hole_hit2.wav
sound/ambience/hole_hit3.wav
sound/ambience/hole_hit4.wav
sound/ambience/hole_hit5.wav
sound/ambience/holy_moly.wav
sound/ambience/im_a_what.wav
sound/ambience/indoor_hallway1.wav
sound/ambience/kramerrrr.wav
sound/ambience/monkey_business.wav
sound/ambience/muffled_clang1.wav
sound/ambience/muffled_clang2.wav
sound/ambience/muffled_clang3.wav
sound/ambience/muffled_clang4.wav
sound/ambience/muffled_clang5.wav
sound/ambience/muffled_clang6.wav
sound/ambience/muffled_clang7.wav
sound/ambience/muffled_clang8.wav
sound/ambience/my_butterfly.wav
sound/ambience/naughty_list.wav
sound/ambience/one_more_nessa.wav
sound/ambience/oui_oui_finzer.wav
sound/ambience/pipe_steam_loop1.wav
sound/ambience/ruby_allnight.wav
sound/ambience/ruby_bomb.wav
sound/ambience/ruby_bzzz.wav
sound/ambience/ruby_commercial.wav
sound/ambience/ruby_count.wav
sound/ambience/ruby_deaf.wav
sound/ambience/ruby_fire.wav
sound/ambience/ruby_green.wav
sound/ambience/ruby_hothothot.wav
sound/ambience/ruby_korben.wav
sound/ambience/ruby_leavin.wav
sound/ambience/ruby_position.wav
sound/ambience/ruby_scream.wav
sound/ambience/ruby_sing.wav
sound/ambience/ruby_unbelievable.wav
sound/ambience/silver_ramble.wav
sound/ambience/sorry_beats.wav
sound/ambience/soupwell_dorian.wav
sound/ambience/splash_impact1.wav
sound/ambience/strange_talk1.wav
sound/ambience/strange_talk10.wav
sound/ambience/strange_talk2.wav
sound/ambience/strange_talk3.wav
sound/ambience/strange_talk4.wav
sound/ambience/strange_talk5.wav
sound/ambience/strange_talk6.wav
sound/ambience/strange_talk7.wav
sound/ambience/strange_talk8.wav
sound/ambience/strange_talk9.wav
sound/ambience/tele_sound1.wav
sound/ambience/tele_zap1.wav
sound/ambience/thanks_yo.wav
sound/ambience/underground_hall_loop1.wav
sound/ambience/useless.wav
sound/ambience/warehouse_ambience_loop1.wav
sound/ambience/wind_med1.wav
sprites/Exit1.spr
sprites/flourecent_glow2.spr
sprites/Tele1.spr
