//wintersedge - The Edge (Quake Live retextured version)

gfx/detail/dt_brick.tga
gfx/detail/dt_carpet1.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_ground4.tga
gfx/detail/dt_ground5.tga
gfx/detail/dt_leather1.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_rough.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_smooth2.tga
gfx/detail/dt_snow1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_snow.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood3.tga
gfx/detail/dt_wood.tga
gfx/env/devilish_bk.tga
gfx/env/devilish_dn.tga
gfx/env/devilish_ft.tga
gfx/env/devilish_lf.tga
gfx/env/devilish_rt.tga
gfx/env/devilish_up.tga
maps/wintersedge.res
maps/wintersedge_detail.txt
sound/hq/am_pkup.wav
sound/hq/ar1_pkup.wav
sound/hq/ar2_pkup.wav
sound/hq/m_health.wav
sound/hq/n_health.wav
sound/hq/q3_pwupspawn.wav
sound/hq/q3track2.wav
sound/hq/s_health.wav
sound/hq/w_pkup.wav
sound/world/drip_amb.wav
sound/world/wind2.wav
sprites/effects/quakelivelogo.spr
entity.wad
