//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/xfire.html
halflife.wad
liquids.wad
decals.wad
cached.wad
gfx.wad
sprites/muzzleflash2.spr
sound/ambience/biggun1.wav
pldecal.wad
maps/xfire.bsp
