//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/tfc/xjbg_climbhop.html
cstrike.wad
timecounter.wad
de_storm.wad
wsp_enclosure.wad
cstraining.wad
cs_oldvillage.wad
de_piranesi.wad
cs_dangerous_mountain2.wad
maps/xjbg_climbhop.bsp
